import itertools
import pprint
import textwrap
from pathlib import Path
from typing import Mapping, Union, Sequence, Dict, Any

import torch

# -----------------------------------------------------------------------------
# Script: inspect_pt_files.py
# Author: Auto-generated by AI assistant on behalf of user
# Purpose: Convenience utility to peek inside several PyTorch ``.pt`` data files
#          without flooding the terminal.  Designed to be run via
#
#     conda activate accelmd && python inspect_pt_files.py
#
#          or with a custom file list, e.g.
#
#     conda activate accelmd && python inspect_pt_files.py \
#         data/pt_dipeptides/AF/adj_list.pt data/pt_dipeptides/AF/atom_types.pt
# -----------------------------------------------------------------------------

# Maximum number of collection elements or tensor values to print per object.
_PREVIEW_LIMIT = 20


def _summarize(name: str, obj: Any) -> None:  # noqa: ANN401
    """Pretty-print a concise summary of *obj*.

    Parameters
    ----------
    name
        Human-readable identifier for the object (usually the filename stem).
    obj
        The Python object loaded via ``torch.load``.
    """
    print(f"\n=== {name} ===")
    print(f"type: {type(obj)}")

    if isinstance(obj, torch.Tensor):
        print(f"shape: {tuple(obj.shape)}, dtype: {obj.dtype}")
        flat = obj.flatten()
        values = flat[:_PREVIEW_LIMIT].tolist()
        suffix = " …" if flat.numel() > _PREVIEW_LIMIT else ""
        print("values:", values, suffix)

    elif isinstance(obj, (list, tuple, set)):
        print(f"length: {len(obj)}")
        preview = list(itertools.islice(obj, _PREVIEW_LIMIT))
        suffix = " …" if len(obj) > _PREVIEW_LIMIT else ""
        pprint.pprint(preview)
        if suffix:
            print(suffix)

    elif isinstance(obj, Mapping):
        print(f"length: {len(obj)} (mapping)")
        items_preview = list(itertools.islice(obj.items(), _PREVIEW_LIMIT))
        pprint.pprint(items_preview)
        if len(obj) > _PREVIEW_LIMIT:
            print(" …")

    else:
        summary = textwrap.shorten(str(obj), width=200, placeholder=" …")
        print(summary)


def _resolve_files(paths: Sequence[str]) -> Dict[str, Path]:
    """Return a mapping of *stem* → *Path* for every provided *paths* argument."""
    out: Dict[str, Path] = {}
    for raw in paths:
        p = Path(raw).expanduser().resolve()
        out[p.stem] = p
    return out


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Inspect PyTorch .pt files.")
    parser.add_argument(
        "files",
        nargs="*",
        default=[
            "data/pt_dipeptides/AA/adj_list.pt",
            "data/pt_dipeptides/AA/atom_types.pt",
            "data/pt_dipeptides/AA/pt_AA.pt",
        ],
        help="Paths to .pt files (default: the three AA dipeptide files).",
    )
    args = parser.parse_args()

    file_map = _resolve_files(args.files)

    for label, path in file_map.items():
        try:
            obj = torch.load(path, map_location="cpu")
        except Exception as exc:  # pylint: disable=broad-except
            print(f"\n=== {label} ===")
            print(f"ERROR loading {path}: {exc}")
            continue
        _summarize(label, obj)


if __name__ == "__main__":
    main() 